version: '3'
services:
    qrcode:
        environment:
          PYTHONUNBUFFERED: 1
          FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
          URL_BASE: "${URL_BASE}"
        build: .
        ports:
            - "5002:5002"
        volumes:
            - .:/app
        networks:
          - default
#;networks:
#   default:
#      external:
#        name: nginxproxymanager_default
